#00:45-01:06
use_bpm 170
use_synth :blade
weight = "C:/Users/dallas_estell/Downloads/song samples/weightless chorus.wav"
mariaout = "C:/Users/dallas_estell/Downloads/song samples/mariafadeout.wav"
l = 0
define :theweight do
  sample t |t, h|
  sleep h
end
live_loop :chorus do
  4.times do
    64.times do
      #first measure 4
      play :a5
      sleep 0.5
      play :a5
      sleep 0.5
      play :a5
      sleep 0.5
      play :g5
      sleep 0.5
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :fs5
      sleep 0.5
      #second measure 4
      play :fs5
      sleep 0.5
      play :g5
      sleep 0.5
      play :g5
      sleep 1
      play :r
      sleep 0.5
      play :r
      sleep 0.5
      play :a4
      sleep 0.5
      #third measure 4
      play :a5
      sleep 0.5
      play :a5
      sleep 0.5
      play :a5
      sleep 0.5
      play :g5
      sleep 0.5
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :e5
      sleep 0.5
      #fourth measure 4
      play :e5
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 0.5
      play :a4
      sleep 0.5
      #fifth measure 4
      play :a5
      sleep 0.5
      play :a5
      sleep 1
      play :g5
      sleep 0.5
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :fs5
      sleep 0.5
      #sixth measure 4
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :g5
      sleep 1
      play :fs5
      sleep 0.5
      #seventh measure 4
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :e5
      sleep 1
      play :e5
      sleep 0.5
      #eigth measure 4
      play :e5
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 0.5
      play :a4
      sleep 0.5
      #nineth measure 4
      play :a5
      sleep 0.5
      play :a5
      sleep 1
      play :g5
      sleep 0.5
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :g5
      sleep 0.5
      #10 4
      play :g5
      sleep 0.5
      play :d5
      sleep 0.5
      play :d5
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 0.5
      play :a4
      sleep 0.5
      #11 4
      play :a5
      sleep 0.5
      play :a5
      sleep 1
      play :g5
      sleep 0.5
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :cs5
      sleep 0.5
      #12 4
      play :b4
      sleep 0.5
      play :r
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 0.5
      play :b4
      sleep 1
      #12 4
      play :a5
      sleep 1
      play :a5
      sleep 1
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :fs5
      sleep 0.5
      #13 4
      play :a5
      sleep 1
      play :a5
      sleep 1
      play :g5
      sleep 0.5
      play :fs5
      sleep 1
      play :fs5
      sleep 0.5
      #14 4
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :fs5
      sleep 0.5
      play :g5
      sleep 1
      play :e5
      sleep 0.5
      #15 4
      play :e5
      sleep 0.5
      play :e5
      sleep 0.5
      play :e5
      sleep 0.5
      play :e5
      sleep 0.5
      play :e5
      sleep 0.5
      play :d5
      sleep 0.5
      play :d5
      sleep 1
      #16 4
      play :d5
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 1
      play :r
      sleep 1
    end
  end
end